apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-developer-ex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pattybardo/argocd-test.git
    targetRevision: HEAD
    path: argocd-application-developer-ex
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
